[functions.google-drive-upload-avatar]
verify_jwt = false
[functions.wompi-generate-checkout]
enabled = true
verify_jwt = true
import_map = "./functions/wompi-generate-checkout/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/wompi-generate-checkout/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/wompi-generate-checkout/*.html" ]

[functions.wompi-webhook-handler]
enabled = true
verify_jwt = true
import_map = "./functions/wompi-webhook-handler/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/wompi-webhook-handler/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/wompi-webhook-handler/*.html" ]

[functions.create-subscription-checkout]
enabled = true
verify_jwt = true
import_map = "./functions/create-subscription-checkout/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/create-subscription-checkout/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/create-subscription-checkout/*.html" ]
