CREATE TABLE public.api_request_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    path TEXT,
    method TEXT,
    status_code INTEGER,
    response_time_ms INTEGER,
    tenant_id UUID REFERENCES public.tenants(id) ON DELETE SET NULL
);

COMMENT ON TABLE public.api_request_metrics IS 'Stores performance metrics for API requests.';
