-- Fase 1.1: Crear la tabla units_of_measure
CREATE TABLE public.units_of_measure (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id UUID REFERENCES public.tenants(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    abbreviation TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    CONSTRAINT uom_tenant_abbreviation_unique UNIQUE (tenant_id, abbreviation)
);

COMMENT ON TABLE public.units_of_measure IS 'Stores units of measure for products, can be tenant-specific or global (null tenant_id).';
COMMENT ON COLUMN public.units_of_measure.tenant_id IS 'The tenant who owns this unit of measure. If NULL, it is a global unit.';
COMMENT ON COLUMN public.units_of_measure.name IS 'The full name of the unit of measure (e.g., "Milliliter").';
COMMENT ON COLUMN public.units_of_measure.abbreviation IS 'The abbreviated name of the unit (e.g., "ml").';


-- Fase 1.2: Modificar la tabla products
ALTER TABLE public.products
ADD COLUMN unit_of_measure_id BIGINT REFERENCES public.units_of_measure(id) ON DELETE SET NULL,
ADD COLUMN package_content_quantity NUMERIC(10, 3) DEFAULT 1 NOT NULL,
ADD COLUMN allow_decimal_sale BOOLEAN DEFAULT FALSE NOT NULL;

COMMENT ON COLUMN public.products.unit_of_measure_id IS 'The unit of measure for this product.';
COMMENT ON COLUMN public.products.package_content_quantity IS 'The quantity of the product in its package, in the specified unit of measure (e.g., 500 for a 500ml bottle).';
COMMENT ON COLUMN public.products.allow_decimal_sale IS 'Whether this product can be sold in fractional quantities.';


-- Fase 1.3: Alterar las tablas de inventario, combos y transferencias
-- branch_products
ALTER TABLE public.branch_products
ALTER COLUMN stock_quantity TYPE NUMERIC(10, 3);

-- combo_items
ALTER TABLE public.combo_items
ALTER COLUMN quantity TYPE NUMERIC(10, 3);

-- product_transfer_items
ALTER TABLE public.product_transfer_items
ALTER COLUMN quantity TYPE NUMERIC(10, 3);

-- product_transfer_reception_items
ALTER TABLE public.product_transfer_reception_items
ALTER COLUMN quantity_expected TYPE NUMERIC(10, 3),
ALTER COLUMN quantity_received TYPE NUMERIC(10, 3);
